name: Continuous Integration

on:
  push:
  pull_request:
    types:
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Run tests
        run: |
          pnpm run test

  lint:
    runs-on: ubuntu-latest
    name: Lint the application
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Run linter
        run: |
          pnpm run lint
