name: Continuous Integration

on:
  push:
  pull_request:
    types:
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: |
          bun install
      - name: Run tests
        run: |
          bun run test

  lint:
    runs-on: ubuntu-latest
    name: Lint the application
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: |
          bun install
      - name: Run linter
        run: |
          bun run lint
